services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: valora
      POSTGRES_USER: valora
      POSTGRES_PASSWORD: valora
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: sleep infinity
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: project.settings
      POSTGRES_DB: valora
      POSTGRES_USER: valora
      POSTGRES_PASSWORD: valora
      POSTGRES_HOST: db
    depends_on:
      - db

volumes:
  postgres_data:
